export class OrderingDto {
  orderingNumber?: string
  carId?: number
  salesEmployeeId?: number
  customerNumber?: string
  additionalOrderId?: number
  discountName?: string
  discountPercentage?: number
  insuranceId?: number
  tradingStatus?: string
  salesType?: string
  paymentType?: number
  orderPrice?: number
  firstPaid?: number
  carPrice?: number
  arrearPaidPrice?: number
  serviceCharge?: number
  derivativePrice?: number
  agentLicensePrice?: number
  agentTaxPrice?: number
  agentGreenBookPrice?: number
  greenBookDeposit?: number
  orderPaidWay?: number
  firstPaidWay?: number
  carPricePaidWay?: number
  arrearPaidWay?: number
  serviceChargePaidWay?: number
  derivativePaidWay?: number
  agentLicensePaidWay?: number
  agentTaxPaidWay?: number
  agentGreenBookPaidWay?: number
  greenBookDepositPaidWay?: number
  orderPriceComment?: string
  firstPaidComment?: string
  carPriceComment?: string
  arrearPaidPriceComment?: string
  serviceChargeComment?: string
  derivativePriceComment?: string
  agentLicensePriceComment?: string
  agentTaxPriceComment?: string
  agentGreenBookPriceComment?: string
  greenBookDepositComment?: string
  isActived?: number
  createdDate?: string
  createdBy?: string
  updatedDate?: string
  updatedBy?: string
}

