export enum BYD_PURCHASE_ORDERING_MAPPING {
  purchaseOrderingNumber = 0,
  carType = 2,
  carTypeCategory = 3,
  carTypeCode = 5,
  carSeries = 6,
  carColor = 8,
  purchaseOrderingStatus = 11,
  purchaseOrderingDate = 12,
  purchaseOrderingPlanningDate = 13,
  carSweptVolume = 15,
  transmission = 16,
  purchaseOrderingCount = 17,
  startPrice = 22,
  purchaseOrderingTotalPrice = 23,
  preSellingPrice = 27,
  paymentType = 29,
  billingNumber = 30,
  cooperationBank = 31,
  billingPrice = 32,
  billingStartDate = 33,
  billingEndDate = 34,
  productionAddress = 39,
  productName = 46
}

export enum BYD_IN_STOREHOUSE_MAPPING {
  vinNumber = 0,
  carSeries = 2,
  productName = 3,
  carType = 4,
  carTypeCategory = 5,
  carTypeCode = 6,
  engineNumber = 8,
  carColor = 10,
  transmission = 11,
  isThirdParty = 13,
  productionDate = 23,
  manufacturedDate = 24,
  certificateNumber = 25,
  certificateLocation = 26,
  purchaseOrderingNumber = 27,
  arriveStoreDate = 28,
  StoreDateCount = 29,
  carStatus = 46,
  purchaseOrderingPlanningDate = 48,
  batteryPackNumber = 52,
  gearboxNumber = 53,
  announcementNumber = 56
}
